# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('abstract', models.CharField(default=b'', help_text=b'The article abstract', max_length=1000)),
            ],
            options={
                'db_table': 'abstract',
            },
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.BigIntegerField(blank=True, db_index=True, help_text="Scopus's auid", null=True)),
                ('initials', models.CharField(default='', max_length=20)),
                ('surname', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='1 for first author, etc. Can have multiple Authorship entries for one value of order.')),
                ('affiliation_id', models.IntegerField(db_index=True, help_text="Scopus's afid", null=True)),
                ('organization', models.CharField(db_index=True, default='', help_text='Name from 1st organization node in affiliation details', max_length=300)),
                ('department', models.CharField(default='', help_text='Name from 2nd organization node in affiliation details', max_length=200)),
                ('country', models.CharField(max_length=10)),
                ('city', models.CharField(help_text='Not currently stored', max_length=30)),
            ],
            options={
                'db_table': 'authorship',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite_to', models.BigIntegerField(db_index=True, default=-1, help_text='EID of document being cited')),
                ('cite_from', models.BigIntegerField(db_index=True, default=-1, help_text='EID (or group ID?) of citing document')),
            ],
            options={
                'db_table': 'citation',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('eid', models.BigIntegerField(help_text=b'A unique identifier for the record; but see group_id', serialize=False, primary_key=True, db_index=True)),
                ('doi', models.CharField(help_text=b'DOI', max_length=150, null=True)),
                ('pub_year', models.IntegerField(default=-1, help_text=b'Publication year recorded in xocs:pub-year, backing off to xocs:sort-year where pub-year is unavailable', db_index=True)),
                ('group_id', models.BigIntegerField(help_text=b'An EID shared by likely duplicate doc entries', null=True, db_index=True, blank=True)),
                ('title', models.CharField(help_text=b'The original (untranslated) title', max_length=400)),
                ('citation_count', models.IntegerField(default=0, help_text=b'Citation count from citedby.xml')),
                ('title_language', models.CharField(default=b'', help_text=b'The language of the original title', max_length=5)),
                ('citation_type', models.CharField(default=b'', help_text=b'The type of document', max_length=5, choices=[(b'ab', b'ab = Abstract Report'), (b'ar', b'ar = Article'), (b'ba', b'ba'), (b'bk', b'bk = Book'), (b'br', b'br = Book Review'), (b'bz', b'bz = Business Article'), (b'cb', b'cb = Conference Abstract'), (b'ch', b'ch = Chapter'), (b'cp', b'cp = Conference Paper'), (b'cr', b'cr = Conference Review'), (b'di', b'di = Dissertation'), (b'ed', b'ed = Editorial'), (b'er', b'er = Erratum'), (b'ip', b'ip = Article in Press'), (b'le', b'le = Letter'), (b'no', b'no = Note'), (b'pa', b'pa = Patent'), (b'pr', b'pr = Press Release'), (b're', b're = Review'), (b'rf', b'rf'), (b'rp', b'rp = Report'), (b'sh', b'sh = Short Survey'), (b'wp', b'wp = Working Paper')])),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='ItemID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, help_text='The identifier', max_length=20)),
                ('item_type', models.CharField(help_text='ItemID type (see Scopus documentation)', max_length=40)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scopus.Document')),
            ],
            options={
                'db_table': 'itemid',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopus_source_id', models.BigIntegerField(db_index=True, default=-1, help_text="Scopus's srcid")),
                ('source_type', models.CharField(choices=[('b', 'b = Book'), ('d', 'd = Trade Journal'), ('j', 'j = Journal'), ('k', 'k = Book Series'), ('m', 'm = Multi-volume Reference Works'), ('p', 'p = Conference Proceeding'), ('r', 'r = Report'), ('n', 'n = Newsletter'), ('w', 'w = Newspaper')], db_index=True, help_text='Source type', max_length=1, null=True)),
                ('source_title', models.CharField(max_length=350)),
                ('source_abbrev', models.CharField(max_length=150)),
                ('issn_print', models.CharField(db_index=True, max_length=15, null=True)),
                ('issn_electronic', models.CharField(db_index=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('scopus_source_id', 'issn_print', 'issn_electronic')]),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Where the document is published', null=True, on_delete=django.db.models.deletion.CASCADE, to='Scopus.Source'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scopus.Document'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='document',
            field=models.ForeignKey(to='Scopus.Document'),
        ),
    ]
