# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-05 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorship',
            name='organization1',
        ),
        migrations.RemoveField(
            model_name='authorship',
            name='organization2',
        ),
        migrations.RemoveField(
            model_name='authorship',
            name='organization3',
        ),
        migrations.AddField(
            model_name='authorship',
            name='affiliation',
            field=models.TextField(db_index=True, default='', help_text='Text from all organization nodes, separated by newline characters'),
        ),
    ]
