# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scopus', '0002_auto_20170905_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemid',
            name='item_id',
            field=models.CharField(db_index=True, help_text='The identifier', max_length=40),
        ),
    ]
